### ISSUE TITLE
Support Node 16.13.1 LTS

### ISSUE THREAD

**Issue by bpetty-interlace** [bragma/winston-azure-application-insights#21]
Using Winston 3.3.3 on Node 14.16.0, everything works in our alpine linux container.
When upgrading the container to 16.13.1 LTS, it dies with the following error:

```
TypeError: Cannot convert a Symbol value to a string
     at zoneAwareAddListener (/usr/src/app/microservice-pdf/ext-lib/node_modules/zone.js/dist/zone-node.js:1136:78)
     at /usr/src/app/microservice-pdf/ext-lib/node_modules/zone.js/dist/zone-node.js:1266:9
     at ReadStream.addListener (eval at createNamedFn (/usr/src/app/microservice-pdf/ext-lib/node_modules/zone.js/dist/zone-node.js:1207:17), <anonymous>:3:38)
     at ReadStream.Readable.on (node:internal/streams/readable:876:35)
     at ReadStream.once (node:events:531:8)
     at Object.construct (node:internal/streams/destroy:240:10)
     at ReadStream.Readable (node:internal/streams/readable:206:15)
     at new ReadStream (node:internal/fs/streams:213:3)
     at Object.createReadStream (node:fs:2869:10)
     at SendStream.stream (/usr/src/app/microservice-pdf/ext-lib/node_modules/send/index.js:796:19)
     at SendStream.send (/usr/src/app/microservice-pdf/ext-lib/node_modules/send/index.js:707:8)
     at onstat (/usr/src/app/microservice-pdf/ext-lib/node_modules/send/index.js:729:10)
     at ZoneDelegate.invokeTask (/usr/src/app/microservice-pdf/ext-lib/node_modules/zone.js/dist/zone-node.js:275:35)
     at Zone.runTask (/usr/src/app/microservice-pdf/ext-lib/node_modules/zone.js/dist/zone-node.js:151:47)
     at ZoneTask.invoke (/usr/src/app/microservice-pdf/ext-lib/node_modules/zone.js/dist/zone-node.js:345:33)
```

**Comment by willmorgan** [comment]
If you upgrade the zone.js dependency or force it using resolutions key, what happens? Would you be able to PR a fix?
